language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run clean
  - npm run build
  - npm run copy-resources
local_dir: src
deploy:
  provider: pages
  local-dir: dist
  skip_cleanup: true
  github_token: $github_token
  on:
    all_branches: true