language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
local_dir: src
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    all_branches: true